# Generated by Django 3.2.6 on 2021-11-27 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('wanted_date', models.DateField(default=django.utils.timezone.now)),
                ('booking_status', models.CharField(choices=[('processing', 'processing'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='processing', max_length=50)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.employeeregister')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userregister')),
            ],
        ),
    ]
