# Generated by Django 3.2.6 on 2021-11-27 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='battery_model',
            field=models.CharField(choices=[('lithium', 'lithium'), ('water', 'water')], default='lithium', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='unit',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
