# Generated by Django 3.2.6 on 2022-01-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20220104_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregister',
            name='availabilty_status',
            field=models.CharField(choices=[('available', 'available'), ('not_available', 'not_available')], default='available', max_length=50),
        ),
    ]
