# Generated by Django 3.2.6 on 2022-01-04 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='boat',
        ),
    ]
